CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC      
      INTEGER HepMC2_new_writer,HepMC2_delete_writer
      INTEGER HepMC2_set_hepevt_address
      INTEGER HepMC2_convert_event,HepMC2_write_event,HepMC2_clear_event
      INTEGER HepMC2_set_attribute_int,HepMC2_set_attribute_double
      INTEGER HepMC2_set_pdf_info,HepMC2_set_cross_section
      INTEGER HepMC2_new_weight
      INTEGER HepMC2_set_weight_by_index
      INTEGER HepMC2_set_weight_by_name
      EXTERNAL HepMC2_new_writer,HepMC2_delete_writer
      EXTERNAL HepMC2_set_hepevt_address
      EXTERNAL HepMC2_convert_event,HepMC2_write_event
      EXTERNAL HepMC2_clear_event
      EXTERNAL HepMC2_set_attribute_int,HepMC2_set_attribute_double
      EXTERNAL HepMC2_set_pdf_info,HepMC2_set_cross_section
      EXTERNAL HepMC2_new_weight
      EXTERNAL HepMC2_set_weight_by_index
      EXTERNAL HepMC2_set_weight_by_name
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC