name: build
on:
 push:
 pull_request:
 schedule:
#Every 2 days at midnight 
    - cron:  "0 0 1/48 * *"

jobs:
  compilejobFedora38:
    name: HEPrpms_on_Fedora38
    runs-on: ubuntu-latest
    container:
        image: fedora:38
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install 
      run: |
           dnf -y install 'dnf-command(copr)' rpm-build which rpmdevtools git
           dnf -y copr enable averbyts/HEPrpms
           pwd
           ls
           sh srpmsbuild.sh HEPrpms 2023.12.30 --build
           dnf -y install HEPrpms/2023.12.30/rpmbuild/RPMS/x86_64/HEPrpms-2023.12.30-1.fc38.x86_64.rpm
